services:
  criptoversus-mcp:
    container_name: criptoversus-mcp
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "8787"
    volumes:
      - ./data:/data
    networks:
      - npm_network

networks:
  npm_network:
    external: true
