# Part 3: public.about, public.scoringRules, public.riskDisclaimer
T3 = {}

def add(p, d):
    for k, v in d.items():
        T3[f"{p}.{k}"] = v

# ===== public.about =====
add("public.about.seo", {"title":"Informazioni su CriptoVersus | Arena Dati di Mercato Pubblica","description":"Scopri come CriptoVersus trasforma i dati pubblici del mercato crypto in simulazioni in stile calcistico per analisi, istruzione e intrattenimento."})
add("public.about.hero", {"eyebrow":"Informazioni","title":"Dati di mercato pubblici, visualizzati come simulazioni in diretta dell'arena.","lead":"CriptoVersus \u00e8 una piattaforma gamificata di visualizzazione dati di mercato. Aiuta gli utenti a esplorare i segnali crypto pubblici, la selezione della squadra e le classifiche in stile partita senza presentarsi come un prodotto finanziario.","backToArena":"Torna all'arena","viewScoringRules":"Vedi le regole di punteggio","panelLabel":"Panoramica CriptoVersus"})
add("public.about.hero.panel", {"publicDataLabel":"Dati pubblici","publicDataTitle":"Segnali di mercato aperti","publicDataBody":"L'arena \u00e8 costruita da segnali pubblici del mercato crypto, non da accesso privato al mercato.","simulationLabel":"Simulazione","simulationTitle":"Visivi in stile calcistico","simulationBody":"Le classifiche in stile partita aiutano le persone a leggere il movimento dei prezzi e il momentum a colpo d'occhio.","useLabel":"Uso responsabile","useTitle":"Analisi prima di tutto","useBody":"Usa il sito per istruzione, intrattenimento e visualizzazione del mercato."})
T3["public.about.sections.overviewLabel"] = "Sezioni informazioni su CriptoVersus"
add("public.about.cards.platform", {"label":"Cos'\u00e8","title":"Un livello pubblico di analisi","body":"CriptoVersus \u00e8 progettato per istruzione, intrattenimento e visualizzazione del mercato attorno ai dati pubblici crypto."})
add("public.about.cards.how", {"label":"Come funziona","title":"I segnali diventano simulazioni","body":"I segnali pubblici vengono raggruppati in viste in stile partita cos\u00ec gli utenti possono ispezionare momentum, pressione e contesto della partita."})
add("public.about.cards.responsible", {"label":"Uso responsabile","title":"Informazioni, non consulenza","body":"La piattaforma non promette profitto, non prevede i prezzi futuri n\u00e9 sostituisce il giudizio indipendente."})
add("public.about.dataSources", {"title":"Fonti Dati","description":"CriptoVersus utilizza dati pubblici del mercato crypto e segnali di mercato, incluse le coppie negoziate su Binance quando disponibili. Questi segnali possono includere il movimento dei prezzi, la variazione percentuale, il comportamento delle candele, l'attivit\u00e0 di trading e altri indicatori derivati dal mercato usati per generare partite simulate in stile calcistico. CriptoVersus non \u00e8 affiliato, approvato, sponsorizzato o ufficialmente connesso a Binance.","binanceNotice":"Quando le coppie negoziate su Binance sono disponibili, sono incluse come una fonte pubblica di mercato tra le altre e non implicano approvazione o partnership.","notAffiliated":"La presenza di una coppia negoziata su Binance non significa approvazione, raccomandazione o validazione dell'asset sottostante.","usage":"I dati sono utilizzati per visualizzazione, analisi, simulazione e intrattenimento.","reliability":"I segnali possono avere ritardi, fallire, divergere o diventare temporaneamente non disponibili."})

# ===== public.scoringRules =====
add("public.scoringRules.seo", {"title":"Regole di Punteggio CriptoVersus | Segnali Pubblici di Mercato","description":"Vedi come i segnali pubblici di mercato diventano eventi di punteggio in CriptoVersus attraverso regole percentuali, di incrocio, di volume e Candle Battle."})
add("public.scoringRules.hero", {"eyebrow":"Regole di punteggio","title":"I segnali pubblici di mercato si trasformano in punteggio della partita.","lead":"CriptoVersus utilizza indicatori derivati dal mercato per creare partite simulate. Il punteggio pubblicato segue l'insieme di regole attivo e dovrebbe essere letto come analisi, non come consulenza finanziaria o previsione dei prezzi.","backToAbout":"Leggi informazioni su CriptoVersus","backToArena":"Torna all'arena","panelLabel":"Panoramica punteggio"})
add("public.scoringRules.hero.panel", {"signalsLabel":"Segnali","signalsTitle":"Input pubblici prima di tutto","signalsBody":"Movimento dei prezzi, variazione percentuale, comportamento delle candele, volume quotato e attivit\u00e0 di trading alimentano l'arena, incluse le coppie negoziate su Binance quando disponibili.","leftTeam":"Lato A","versus":"vs","simulated":"Partita simulata","rightTeam":"Lato B","scoringLabel":"Punteggio","scoringTitle":"Eventi della partita","scoringBody":"Quei input pubblici possono creare eventi di punteggio attraverso soglie percentuali, incroci, finestre di volume, incroci di volume e dominanza Candle Battle.","resultLabel":"Risultati","resultTitle":"Leader finale o nessuno","resultBody":"Un ciclo pu\u00f2 terminare con un leader finale o senza leader finale, e il punteggio non prevede i prezzi futuri dei token."})
add("public.scoringRules.sections", {"overviewLabel":"Panoramica regole di punteggio","overviewEyebrow":"Come si legge l'arena","overviewTitle":"Segnali pubblici, regole chiare, cicli visibili.","overviewLead":"Questa pagina spiega come i segnali pubblici di mercato diventano eventi di punteggio, come avanza la partita simulata e come la classifica pubblica dovrebbe essere interpretata.","realRulesLabel":"Regole reali","realRulesEyebrow":"Cosa assegna effettivamente i punti","realRulesTitle":"Solo le regole di punteggio documentate creano eventi di punteggio.","realRulesLead":"L'arena pubblica utilizza regole specifiche per punteggio percentuale, incrocio, volume e Candle Battle. I widget visivi possono aiutare a leggere la partita, ma non sostituiscono il motore delle regole.","simulationsLabel":"Simulazioni","simulationsEyebrow":"Come viene presentato il ciclo","simulationsTitle":"Ogni ciclo \u00e8 mostrato come una partita simulata.","simulationsLead":"La pagina pubblica usa una timeline in stile partita cos\u00ec le persone possono comprendere il flusso dei segnali senza scambiare l'arena per un prodotto di trading.","simulationsTimelineLabel":"Timeline simulazione","visualIndicatorsLabel":"Indicatori visivi","visualIndicatorsEyebrow":"Contesto utile","visualIndicatorsTitle":"Alcuni pannelli sono solo visivi.","visualIndicatorsLead":"Arena Pressure, Momentum e il flusso di mercato aiutano a spiegare lo stato della partita. Sono indicatori visivi, non trigger di punteggio di per s\u00e9.","meaningLabel":"Cosa significa il punteggio"})
add("public.scoringRules.cards.signals", {"label":"Raccolta segnali","title":"I dati pubblici di mercato vengono letti","body":"La piattaforma legge il movimento del mercato, la variazione percentuale, il comportamento delle candele, il volume quotato e l'attivit\u00e0 di trading da fonti pubbliche, incluse le coppie negoziate su Binance quando disponibili."})
add("public.scoringRules.cards.scoring", {"label":"Eventi di punteggio","title":"I segnali diventano eventi di punteggio","body":"Le regole di soglia percentuale assegnano punti quando il divario raggiunge i livelli configurati. Le regole di incrocio assegnano punti solo quando un lato si sposta da sotto a sopra l'avversario. Le regole di finestra di volume e incrocio di volume seguono la stessa logica di segnale pubblico sul volume quotato, mentre la dominanza Candle Battle aggiunge un percorso di punteggio separato."})
add("public.scoringRules.cards.settlement", {"label":"Esito del ciclo","title":"Il ciclo si chiude pulitamente","body":"Il punteggio pubblicato \u00e8 una visualizzazione educativa del comportamento del mercato. Non \u00e8 consulenza di investimento, un segnale di trading o un risultato garantito."})
add("public.scoringRules.rules.percentage", {"label":"Regola percentuale","title":"Soglie percentuali","body":"I punti possono essere assegnati quando il divario percentuale relativo raggiunge le soglie configurate.","point1":"La variazione percentuale pi\u00f9 ampia guida la regola.","point2":"Ogni soglia configurata pu\u00f2 essere conteggiata una volta per lato.","point3":"Il punteggio riflette il movimento pubblico del mercato, non le performance future."})
add("public.scoringRules.rules.crossover", {"label":"Regola incrocio","title":"Incrocio percentuale","body":"I punti possono essere assegnati quando un lato incrocia da sotto a sopra l'altro lato sul movimento percentuale.","point1":"L'incrocio deve muoversi verso l'alto attraverso l'avversario.","point2":"Toccare la linea non \u00e8 sufficiente se non si verifica un incrocio.","point3":"Questa \u00e8 una regola di segnale di mercato, non consulenza finanziaria."})
add("public.scoringRules.rules.candleBattle", {"label":"Regola Candle Battle","title":"Dominanza Candle Battle","body":"I punti possono essere assegnati quando la dominanza Candle Battle diventa chiara dalla sequenza di candele.","point1":"La regola confronta il movimento relativo candela-per-candela.","point2":"Una sequenza pi\u00f9 forte pu\u00f2 creare un evento di punteggio.","point3":"\u00c8 una partita simulata basata su dati pubblici di mercato."})
add("public.scoringRules.rules.dominance", {"label":"Regola dominanza","title":"Dominanza continua","body":"La dominanza sostenuta pu\u00f2 mantenere stabile il leader della partita e rendere il risultato pi\u00f9 facile da leggere.","point1":"La regola segue lo stato di dominanza attiva.","point2":"Riflette il controllo della partita, non un risultato garantito.","point3":"La classifica rimane una visualizzazione educativa."})
add("public.scoringRules.simulations.step1", {"title":"1. I segnali vengono raccolti","body":"I dati pubblici di mercato vengono raccolti dalle fonti disponibili e normalizzati per la partita."})
add("public.scoringRules.simulations.step2", {"title":"2. Le regole creano eventi di punteggio","body":"L'insieme di regole attivo trasforma i movimenti di mercato qualificanti in eventi di punteggio."})
add("public.scoringRules.simulations.step3", {"title":"3. Il ciclo si chiude","body":"La partita simulata termina con un leader finale o senza leader finale."})
add("public.scoringRules.indicators.arenaPressure", {"label":"Arena Pressure","title":"Indicatore visivo di pressione","body":"Mostra il contesto della pressione dell'arena come indicatore dell'intensit\u00e0 della partita. Non assegna punti di per s\u00e9."})
add("public.scoringRules.indicators.momentum", {"label":"Momentum","title":"Equilibrio Momentum","body":"Mostra quale lato ha attualmente un Momentum di mercato pi\u00f9 forte. \u00c8 un indicatore visivo, non una regola di punteggio di per s\u00e9."})
add("public.scoringRules.indicators.marketFlow", {"label":"Flusso di mercato","title":"Riepilogo flusso recente","body":"Riassume la direzione recente dei segnali pubblici di mercato cos\u00ec la partita \u00e8 pi\u00f9 facile da interpretare."})
add("public.scoringRules.meaning.notAdvice", {"label":"Nessuna consulenza finanziaria","title":"Nessuna consulenza finanziaria","body":"CriptoVersus \u00e8 per analisi, istruzione e intrattenimento. Non dice agli utenti cosa comprare, vendere o detenere."})
add("public.scoringRules.meaning.notPrediction", {"label":"Nessuna previsione","title":"Nessuna previsione","body":"Il punteggio non \u00e8 una previsione dei prezzi futuri dei token o della direzione del mercato."})
add("public.scoringRules.meaning.notGuarantee", {"label":"Nessuna garanzia","title":"Nessuna garanzia","body":"I punteggi e i risultati simulati non sono promesse di performance future."})
add("public.scoringRules", {"dataSourcesNoticeLabel":"Nota fonte dati","dataSourcesNoticeTitle":"Fonti dati","dataSourcesNotice":"Gli eventi di punteggio sono generati da segnali pubblici di mercato, incluse le coppie negoziate su Binance quando disponibili. CriptoVersus non \u00e8 affiliato o approvato da Binance."})
add("public.scoringRules.noPrediction", {"label":"Significato","title":"Nessun livello predittivo","body":"Il punteggio di una partita \u00e8 una visualizzazione educativa del comportamento del mercato. Non \u00e8 consulenza di investimento, un segnale di trading o un risultato garantito."})

# ===== public.riskDisclaimer =====
add("public.riskDisclaimer.seo", {"title":"Avvertenza sul Rischio | CriptoVersus","description":"Leggi l'avvertenza sul rischio, i dati e l'uso per CriptoVersus prima di interpretare i punteggi delle partite o le simulazioni di mercato."})
add("public.riskDisclaimer.hero", {"eyebrow":"Avvertenza sul rischio","title":"Usa l'arena come visualizzazione, non come consulenza.","lead":"CriptoVersus \u00e8 per analisi, istruzione e intrattenimento. Non fornisce consulenza finanziaria, raccomandazioni di investimento o risultati garantiti.","backToAbout":"Informazioni su CriptoVersus","backToScoringRules":"Regole di punteggio","panelLabel":"Riepilogo rischio"})
add("public.riskDisclaimer.hero.panel", {"adviceLabel":"Consulenza","adviceTitle":"Nessuna consulenza finanziaria","adviceBody":"Il sito non ti dice cosa comprare, vendere o detenere.","dataLabel":"Qualit\u00e0 dei dati","dataTitle":"I dati pubblici possono cambiare","dataBody":"Le fonti pubbliche possono avere ritardi, fallire, divergere o diventare temporaneamente non disponibili.","outcomeLabel":"Risultato","outcomeTitle":"Nessun risultato garantito","outcomeBody":"I punteggi e i risultati simulati non sono promesse di performance future."})
T3["public.riskDisclaimer.sections.overviewLabel"] = "Sezioni avvertenza sul rischio"
add("public.riskDisclaimer.cards.noAdvice", {"label":"Consulenza","title":"Nessuna consulenza finanziaria","body":"La piattaforma non ti dice cosa comprare, vendere o detenere."})
add("public.riskDisclaimer.cards.data", {"label":"Dati","title":"I segnali possono cambiare","body":"Le fonti pubbliche possono avere ritardi, fallire, divergere o diventare temporaneamente non disponibili."})
add("public.riskDisclaimer.cards.outcome", {"label":"Risultato","title":"Nessun risultato garantito","body":"I punteggi e i risultati simulati non sono promesse di performance future."})
add("public.riskDisclaimer", {"dataProviderNoticeLabel":"Avviso fornitore dati","dataProviderNotice":"CriptoVersus utilizza dati pubblici del mercato crypto e segnali di mercato. Quando le coppie negoziate su Binance sono disponibili, possono far parte del mix. La piattaforma non \u00e8 affiliata o approvata da Binance.","dataProviderNote":"La presenza di una coppia negoziata su Binance non significa approvazione, raccomandazione o validazione dell'asset sottostante.","dataProviderNoGuarantee":"La piattaforma \u00e8 costruita per visualizzazione, analisi, simulazione e intrattenimento, non come prodotto di investimento o servizio con rendimento garantito."})