# Part 5: tv section (very large)
T5 = {}

def add(p, d):
    for k, v in d.items():
        T5[f"{p}.{k}"] = v

add("tv.seo", {"title":"CriptoVersus TV | Broadcast dati di mercato crypto in diretta","description":"Broadcast automatico senza login per OBS Studio con simulazioni di mercato in diretta, classifiche pubbliche e statistiche di mercato da CriptoVersus.","broadcastTitle":"CriptoVersus TV Broadcast | Feed dati di mercato pronto per OBS","broadcastDescription":"Scena CriptoVersus TV pronta per il broadcast per YouTube e OBS con simulazioni di mercato in diretta rotanti, commento deterministico, ticker e supporto audio crowd ambientale.","matchTitle":"{0} vs {1} | CriptoVersus TV","matchDescription":"Guarda {0} vs {1} su CriptoVersus TV con l'overlay dell'arena in diretta, il commento dell'arena e la telemetria pubblica di mercato.","matchDescriptionFallback":"Scena CriptoVersus TV in diretta mercato ottimizzata per broadcast browser-source in OBS Studio."})
add("tv", {"disclaimer":"CriptoVersus \u00e8 una piattaforma gamificata di visualizzazione dati di mercato. I punteggi delle partite sono generati da segnali pubblici di mercato e non devono essere interpretati come consulenza finanziaria, raccomandazioni di investimento, risultati di scommessa o risultati garantiti.","title":"CriptoVersus TV","subtitle":"Broadcast automatico dell'arena crypto in diretta","liveNow":"In diretta ora","startingSoon":"Inizio a breve","ended":"Terminato","watchMatch":"Guarda partita","watchLive":"Guarda in Diretta","openMatch":"Apri Partita","matchNotFound":"Partita non trovata su CriptoVersus TV.","loading":"Caricamento broadcast TV...","offline":"Broadcast offline","vs":"VS","score":"Punteggio","momentum":"Momentum","goals":"Goal","refreshing":"Aggiornamento","liveArena":"Arena in diretta","poweredBy":"Offerto da CriptoVersus","noMatches":"Nessuna partita disponibile in questo momento."})
add("tv.matchPage", {"eyebrow":"TV Partita","loading":"Caricamento partita...","loadingBody":"L'arena sta preparando l'accoppiamento in diretta.","notFound":"Partita non trovata.","notFoundBody":"Non abbiamo potuto localizzare la partita richiesta. Scegli un'altra arena o torna al canale TV.","unavailable":"Questa partita \u00e8 terminata","unavailableBody":"Continua a guardare con la prossima partita disponibile, sfoglia l'elenco delle partite, o torna al canale TV automatico.","error":"Impossibile caricare l'arena in questo momento.","errorBody":"Riprova tra un momento. Se il problema persiste, il broadcast potrebbe essere ancora in aggiornamento.","watchNext":"Guarda la prossima partita","viewMatches":"Vedi altre partite","returnToTv":"Torna alla TV","returnHome":"Torna alla home","retry":"Riprova"})
add("tv.futurebol", {"canvasAriaLabel":"Campo 3D Futurebol","loading":"Caricamento arena...","loadingSlow":"L'arena sta impiegando un po' di pi\u00f9 per caricarsi...","error":"Impossibile caricare l'arena 3D.","errorBody":"Riprova o ricarica la pagina.","retry":"Riprova"})
add("tv.hero", {"eyebrow":"Broadcast automatico","title":"CriptoVersus TV"})
add("tv.states", {"waitingForNextHotBattle":"In attesa della prossima battaglia calda","proceduralSearchTitle":"Ricerca della prossima battaglia procedurale...","proceduralSearchSubtitle":"Analisi dell'impulso di mercato, delle classifiche e dei possibili contendenti","noHotMatchRightNow":"Nessuna partita calda in questo momento","availableInOtherLanguage":"Disponibile anche in un'altra lingua: {0}","aiCalibrating":"Il narratore IA sta calibrando il feed dell'arena.","aiTracking":"Il narratore IA sta tracciando il flusso in diretta per la prossima chiamata.","commentaryLoading":"Il commento dell'arena si sta aggiornando dallo stato pi\u00f9 recente del mercato.","commentaryStandby":"Il commento dell'arena \u00e8 in attesa del prossimo movimento rilevante.","scanMarketPulse":"Sincronizzazione impulso di mercato...","scanArenaRanking":"Lettura classifica arena...","scanCandidates":"Ricerca coin candidate...","awaitingKickoff":"In attesa dell'evento di kickoff...","initialLoadingTitle":"Caricamento arena...","initialLoadingSubtitle":"Attendi mentre il broadcast conferma i dati della partita.","initialLoadingStepOne":"Sincronizzazione partita","initialLoadingStepTwo":"Preparazione grafici e classifica","initialLoadingStepThree":"Attivazione broadcast"})
add("tv.activity", {"eyebrow":"Attivit\u00e0 in Diretta","title":"Attivit\u00e0 Partita","description":"Eventi, pressione, momentum e cambiamenti tattici che accadono in tempo reale.","ariaLabel":"Grafico attivit\u00e0 partita nel tempo"})
add("tv.labels", {"liveArena":"Arena in Diretta","automaticBroadcast":"Broadcast automatico","hotMatch":"Partita calda","volume":"Volume","realMatch":"Partita reale","matchIdValue":"Partita #{0}","momentum":"Momentum","reversalDetected":"Inversione rilevata","nextBattle":"Prossima battaglia","hotScore":"HotScore","matchClock":"Orologio partita","remaining":"Rimanente","live":"In diretta","firstHalf":"1\u00b0 TEMPO","halfTime":"INTERVALLO","secondHalf":"2\u00b0 TEMPO","final":"FINALE","change":"Cambio","remainingTime":"Tempo rimanente","reason":"Motivo","competitivePool":"Pool partita","arenaCycle":"Ciclo arena","leader":"Leader","pressure":"Pressione","assetPerformance":"Performance asset","candleBattle":"Candle Battle","candlesWon":"Candele vinte","momentumCurrent":"Momentum attuale","tacticalPanel":"Pannello tattico","tacticalPanelA11y":"Pannello tattico Candle Battle","leadership":"Leadership","candlesAnalyzed":"Candele analizzate","currentStreak":"Serie attuale","lastCandle":"Ultima candela","lastVariation":"Ultima variazione","waitingCandleHistory":"In attesa della cronologia candele","chartForAsset":"Candele per {0}","candleBattleA11y":"Arena candle battle {0} vs {1}","controlsCandlesBy":"{0} controlla le candele","pressureAdvantageBy":"vantaggio pressione {0}","momentumNeutral":"Momentum neutro","leftAssetChange":"Variazione asset sinistro","rightAssetChange":"Variazione asset destro","assetVariationA":"Variazione asset A","assetVariationB":"Variazione asset B","assetA":"Asset A","assetB":"Asset B","comparisonChart":"Grafico confronto normalizzato per {0} e {1}","normalizedSharedScale":"Base 1.000 \u00b7 scala condivisa","won":"vinto","tie":"Pareggio","winnerPerCandle":"Leader per candela","competitiveness":"Competitivit\u00e0","poolStatus":"Stato pool","poolStatusActiveFlow":"Flusso in diretta attivo","poolStatusIdle":"Bassa attivit\u00e0 partita","poolStatusBalanced":"Pool partita bilanciato","poolStatusOpen":"Pool partita aperto","eventZone":"Zona eventi","marketDrivenArena":"Arena guidata dal mercato","liveRewardDynamics":"Dinamiche punteggio in diretta","sideCompetition":"Competizione laterale","tiePressure":"Pressione arena bilanciata","onePointBattle":"Battaglia in diretta di un punto","completed":"Completata","pressureRising":"pressione {0} in aumento","signalStable":"Segnale stabile","matchArena":"Arena partita","broadcastTicker":"Ticker broadcast","aiCommentary":"Commento IA","remainingWithClock":"Rimanente ({0})","pressureSummary":"Pool partita | {0} | {1}","marketBattleFlow":"Flusso battaglia di mercato","assetVariationSplit":"Divisione variazione asset","testCommentary":"Commento di test","liveNarrator":"Narratore in diretta","aiMetaTimestamp":"{0} | {1} UTC","commentaryMetaTimestamp":"{0} | {1} UTC"})
T5["tv.labels.activity.eyebrow"] = "Attivit\u00e0 in Diretta"
T5["tv.labels.activity.title"] = "Attivit\u00e0 Partita"
T5["tv.labels.activity.description"] = "Eventi, pressione, momentum e cambiamenti tattici che accadono in tempo reale."
T5["tv.labels.activity.ariaLabel"] = "Grafico attivit\u00e0 partita nel tempo"
add("tv.priceBattle", {"eyebrow":"Confronto prezzi","title":"Battaglia prezzi in diretta","subtitle":"Snapshot di mercato per entrambi i lati della partita.","centerHint":"Confronto mercato in tempo reale","currentPrice":"Prezzo attuale","change":"Variazione","competitiveness":"Competitivit\u00e0","chartAria":"Grafico confronto prezzi in diretta","noData":"In attesa dati prezzi","waitingHistory":"In attesa cronologia prezzi","logoAlt":"Logo di {0}","ariaLabel":"{0} versus {1}, competitivit\u00e0 {2}."})
add("tv.broadcast", {"switchingArena":"Passaggio alla prossima arena calda...","nextHotArena":"La rotazione in diretta si sta spostando verso una finestra dell'arena pi\u00f9 forte.","rotationGaugeLabel":"Rotazione partite","focusGaugeLabel":"Focus telecamera","rotationGaugeTitle":"Prossimo cambio arena tra {0} min","goalLogEmpty":"Nessun goal recente in questa partita.","mainMatchEyebrow":"Partita broadcast in evidenza","mainMatchDescription":"Apri la versione fissa di questa partita per guardare il broadcast completo senza perdere il contesto in diretta.","mainMatchCta":"Entra nel Broadcast","openBroadcastAria":"Apri il broadcast fisso per {0}","overlayTitle":"Guarda il Broadcast","overlaySubtitle":"In diretta ora","signalDegraded":"Segnale degradato","dataStatusTitle":"Feed in esecuzione su dati di recupero","dataStatusFallback":"Il broadcast resta online con l'ultimo snapshot valido mentre l'arena ricostruisce il flusso in diretta.","dataStatusWorkerHeartbeat":"Il worker ha perso i battiti cardiaci recenti. Il broadcast resta online con dati stabili finch\u00e9 la pipeline riprende.","dataStatusWorkerDegraded":"Il worker \u00e8 entrato in modalit\u00e0 degradata. L'arena ha mantenuto il segnale online con dati di fallback invece di cancellare i pannelli.","dataStatusCurrencyMissing":"Lo snapshot pubblico della valuta \u00e8 mancante in questo momento. Lo schermo sta mantenendo l'ultimo frame affidabile.","dataStatusCurrencyStale":"Lo snapshot di mercato \u00e8 diventato obsoleto. Il broadcast sta ancora mostrando l'ultima classifica utile mentre l'ingestion si riprende.","dataStatusStatsStale":"Le statistiche pubbliche sono temporaneamente obsolete. L'arena resta online con i dati pi\u00f9 recenti disponibili."})
add("tv.pressureGauge", {"title":"ARENA PRESSURE","subtitle":"POSSESSO PALLA IN DISPUTA","pressureLabel":"PRESSIONE","currentPressureLabel":"PRESSIONE ATTUALE","momentumLabel":"MOMENTUM","pressureTooltip":"{0} {1} - {2}% pressione","logoAlt":"Logo {0}","ariaLabel":"{0} con {1}% pressione, {2} con {3}% pressione. Stato attuale: {4}.","statusCritical":"{0} PRESSIONE CRITICA","statusControlsArena":"{0} CONTROLLA L'ARENA","statusBalanced":"DUELLO BILANCIATO","statusTransition":"POSSESSO IN TRANSIZIONE","footerInDispute":"IN DISPUTA","footerPressuring":"{0} PRESSIONA","footerNeutralPossession":"POSSESSO NEUTRO","footerLeftDominant":"LATO SINISTRO DOMINANTE","footerRightDominant":"LATO DESTRO DOMINANTE","momentumStrong":"MOMENTUM FORTE","momentumRising":"PRESSIONE IN AUMENTO","momentumNeutral":"RITMO NEUTRO","momentumRecovering":"RECUPERO","description":"La pressione dell'arena mostra il controllo territoriale e l'intensit\u00e0 di ogni lato. Sopra il 60% significa dominanza forte. Sotto il 40% significa perdita di controllo."})
add("tv.modes", {"kicker":"Navigazione TV","title":"Scegli come guardare","description":"Resta sul canale rotativo o apri una partita fissa in diretta.","rotativeEyebrow":"TV Rotativa","rotativeTitle":"Rotazione automatica in diretta","rotativeDescription":"Il canale continua a ruotare tra le arene idonee pi\u00f9 forti.","rotativeCta":"Guarda in Diretta","matchEyebrow":"Partita disponibile","openMatchCta":"Apri Partita","watchLiveCta":"TV Rotativa"})
add("tv.promo", {"chooseSide":"SCEGLI UN LATO!","site":"CRIPTOVERSUS.COM"})
add("tv.audio", {"crowdEnabled":"Audio folla attivo","crowdMuted":"Audio folla silenziato","startBroadcast":"Avvia Audio Broadcast"})
add("tv.field", {"scoreboard":"Classifica arena","remainingTime":"Tempo rimanente","possession":"Possesso","liveArena":"Arena in diretta","automaticBroadcast":"Broadcast automatico","stableSignal":"Segnale stabile","volume":"Volume","momentum":"Momentum","reason":"Motivo","leader":"Leader","pressure":"Pressione","assetVariationA":"Variazione Asset A","assetVariationB":"Variazione Asset B","competitiveness":"Competitivit\u00e0","poolStatus":"Stato pool","recentEvents":"Eventi recenti","goalFor":"{0} ha segnato un punto!","reducedScore":"{0} ha accorciato le distanze","openedScore":"{0} ha aperto le marcature","marketGuidedArena":"Arena guidata dal mercato","eventZone":"Zona eventi","arenaCommentary":"Commento arena","recentEventsFallbackTight":"L'arena \u00e8 ancora bloccata a centrocampo.","recentEventsFallbackLead":"Il leader continua a spingere l'arena avanti."})
T5["tv.grid.metrics.goals"] = "Goal"
add("tv.commentary", {"title":"Commento arena","fallback":"{0} e {1} restano attivi sulla classifica in diretta mentre l'arena aspetta la prossima mossa."})
add("tv.commentary.source", {"template":"Motore template","aiDisabled":"IA disabilitata"})
add("tv.commentary", {"momentumEven":"Momentum bilanciato","momentumFor":"Momentum per {0}"})