using System;
using DAL.NftFutebol;
using EthicAI.EntityModel;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EthicAIDbContext))]
    [Migration("20260421150000_MatchScoringModes")]
    public partial class MatchScoringModes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var defaultRule = MatchScoringRuleType.PercentThreshold.ToString();

            migrationBuilder.Sql($"""
                ALTER TABLE match
                    ADD COLUMN IF NOT EXISTS in_scoring_rule character varying(40) NOT NULL DEFAULT '{defaultRule}';

                ALTER TABLE currency
                    ADD COLUMN IF NOT EXISTS nr_quote_volume decimal(28,8) NOT NULL DEFAULT 0;

                ALTER TABLE currency
                    ADD COLUMN IF NOT EXISTS nr_trades_count bigint NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS match_score_state (
                    cd_match integer NOT NULL PRIMARY KEY,
                    nr_thresholds_awarded_a integer NOT NULL DEFAULT 0,
                    nr_thresholds_awarded_b integer NOT NULL DEFAULT 0,
                    cd_last_percentage_leader integer NULL,
                    cd_last_volume_leader integer NULL,
                    dt_last_volume_window_start timestamp with time zone NULL,
                    dt_last_volume_window_end timestamp with time zone NULL,
                    nr_last_event_sequence integer NOT NULL DEFAULT 0,
                    dt_last_snapshot_at timestamp with time zone NULL,
                    dt_created_at timestamp with time zone NOT NULL,
                    dt_updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT FK_match_score_state_match_cd_match
                        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS match_metric_snapshot (
                    cd_match_metric_snapshot bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cd_match integer NOT NULL,
                    cd_team integer NOT NULL,
                    dt_captured_at timestamp with time zone NOT NULL,
                    nr_percentage_change decimal(18,8) NOT NULL,
                    nr_quote_volume decimal(28,8) NOT NULL,
                    nr_trade_count bigint NOT NULL,
                    CONSTRAINT FK_match_metric_snapshot_match_cd_match
                        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE,
                    CONSTRAINT FK_match_metric_snapshot_team_cd_team
                        FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS match_score_event (
                    cd_match_score_event bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cd_match integer NOT NULL,
                    cd_team integer NOT NULL,
                    in_rule_type character varying(40) NOT NULL,
                    tx_event_type character varying(80) NOT NULL,
                    tx_reason_code character varying(80) NULL,
                    nr_points integer NOT NULL,
                    nr_event_sequence integer NOT NULL,
                    nr_team_percentage_change decimal(18,8) NULL,
                    nr_opponent_percentage_change decimal(18,8) NULL,
                    nr_team_quote_volume decimal(28,8) NULL,
                    nr_opponent_quote_volume decimal(28,8) NULL,
                    nr_metric_delta decimal(28,8) NULL,
                    dt_window_start timestamp with time zone NULL,
                    dt_window_end timestamp with time zone NULL,
                    tx_description text NOT NULL,
                    dt_event_time timestamp with time zone NOT NULL,
                    CONSTRAINT FK_match_score_event_match_cd_match
                        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE,
                    CONSTRAINT FK_match_score_event_team_cd_team
                        FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS IX_match_metric_snapshot_cd_match_cd_team_dt_captured_at
                    ON match_metric_snapshot (cd_match, cd_team, dt_captured_at);

                CREATE INDEX IF NOT EXISTS IX_match_metric_snapshot_cd_team
                    ON match_metric_snapshot (cd_team);

                CREATE UNIQUE INDEX IF NOT EXISTS IX_match_score_event_cd_match_nr_event_sequence
                    ON match_score_event (cd_match, nr_event_sequence);

                CREATE INDEX IF NOT EXISTS IX_match_score_event_cd_team
                    ON match_score_event (cd_team);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "match_metric_snapshot");

            migrationBuilder.DropTable(
                name: "match_score_event");

            migrationBuilder.DropTable(
                name: "match_score_state");

            migrationBuilder.DropColumn(
                name: "in_scoring_rule",
                table: "match");

            migrationBuilder.DropColumn(
                name: "nr_quote_volume",
                table: "currency");

            migrationBuilder.DropColumn(
                name: "nr_trades_count",
                table: "currency");
        }
    }
}
