using EthicAI.EntityModel;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EthicAIDbContext))]
    [Migration("20260509193000_PersistentPositionLayer")]
    public partial class PersistentPositionLayer : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE user_team_position
                    ADD COLUMN IF NOT EXISTS tx_blockchain_mode_snapshot character varying(32);

                ALTER TABLE user_team_position
                    ADD COLUMN IF NOT EXISTS in_exposure_mode integer NOT NULL DEFAULT 0;

                ALTER TABLE user_team_position
                    ADD COLUMN IF NOT EXISTS nr_total_pnl decimal(18, 8) NOT NULL DEFAULT 0;

                ALTER TABLE user_team_position
                    ADD COLUMN IF NOT EXISTS nr_total_wins integer NOT NULL DEFAULT 0;

                ALTER TABLE user_team_position
                    ADD COLUMN IF NOT EXISTS nr_total_losses integer NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS position_allocation (
                    id_position_allocation integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
                    cd_match integer NOT NULL REFERENCES match (cd_match) ON DELETE CASCADE,
                    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
                    nr_allocated_amount decimal(18, 8) NOT NULL,
                    nr_result_amount decimal(18, 8) NULL,
                    nr_pnl decimal(18, 8) NULL,
                    in_status integer NOT NULL DEFAULT 0,
                    dt_created timestamp with time zone NOT NULL,
                    dt_settled timestamp with time zone NULL
                );

                CREATE UNIQUE INDEX IF NOT EXISTS IX_position_allocation_cd_position_cd_match
                    ON position_allocation (cd_position, cd_match);

                CREATE UNIQUE INDEX IF NOT EXISTS IX_position_allocation_cd_bet
                    ON position_allocation (cd_bet)
                    WHERE cd_bet IS NOT NULL;

                CREATE INDEX IF NOT EXISTS IX_position_allocation_cd_match
                    ON position_allocation (cd_match);

                CREATE TABLE IF NOT EXISTS position_lifecycle_event (
                    id_position_lifecycle_event integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
                    cd_match integer NULL REFERENCES match (cd_match) ON DELETE SET NULL,
                    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
                    in_event_type integer NOT NULL,
                    nr_amount decimal(18, 8) NULL,
                    nr_capital_before decimal(18, 8) NULL,
                    nr_capital_after decimal(18, 8) NULL,
                    nr_pnl decimal(18, 8) NULL,
                    tx_notes text NULL,
                    dt_created timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_position_dt_created
                    ON position_lifecycle_event (cd_position, dt_created);

                CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_match
                    ON position_lifecycle_event (cd_match);

                CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_bet
                    ON position_lifecycle_event (cd_bet);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "position_allocation");

            migrationBuilder.DropTable(
                name: "position_lifecycle_event");

            migrationBuilder.DropColumn(
                name: "tx_blockchain_mode_snapshot",
                table: "user_team_position");

            migrationBuilder.DropColumn(
                name: "in_exposure_mode",
                table: "user_team_position");

            migrationBuilder.DropColumn(
                name: "nr_total_losses",
                table: "user_team_position");

            migrationBuilder.DropColumn(
                name: "nr_total_pnl",
                table: "user_team_position");

            migrationBuilder.DropColumn(
                name: "nr_total_wins",
                table: "user_team_position");
        }
    }
}
