START TRANSACTION;

CREATE TABLE audio_asset (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    team_symbol character varying(20),
    context_key character varying(100),
    intensity character varying(30),
    voice_key character varying(80),
    template_key character varying(100),
    text_prompt text,
    audio_url text NOT NULL,
    relative_path text NOT NULL,
    file_name character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL DEFAULT 'audio/mpeg',
    duration_ms integer,
    file_size_bytes bigint,
    file_hash character varying(128),
    generation_model character varying(100),
    generation_source character varying(50),
    quality_score numeric(5,2),
    priority integer NOT NULL DEFAULT 0,
    usage_count integer NOT NULL DEFAULT 0,
    status character varying(30) NOT NULL DEFAULT 'ready',
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    last_used_at_utc timestamp with time zone,
    CONSTRAINT "PK_audio_asset" PRIMARY KEY (id)
);

CREATE TABLE audio_phrase_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    template_key character varying(100) NOT NULL,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    context_key character varying(100),
    intensity character varying(30),
    template_text text NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    priority integer NOT NULL DEFAULT 0,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audio_phrase_template" PRIMARY KEY (id)
);

CREATE TABLE audio_voice_profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    voice_key character varying(80) NOT NULL,
    language character varying(10) NOT NULL,
    display_name character varying(150) NOT NULL,
    sample_relative_path text NOT NULL,
    sample_url text NOT NULL,
    provider character varying(80),
    voice_style character varying(80),
    is_active boolean NOT NULL DEFAULT TRUE,
    priority integer NOT NULL DEFAULT 0,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audio_voice_profile" PRIMARY KEY (id)
);

CREATE TABLE audio_generation_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    team_symbol character varying(20),
    context_key character varying(100),
    intensity character varying(30),
    voice_key character varying(80) NOT NULL,
    template_key character varying(100),
    text_prompt text NOT NULL,
    target_relative_path text,
    target_file_name character varying(255),
    status character varying(30) NOT NULL DEFAULT 'pending',
    priority integer NOT NULL DEFAULT 0,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    lease_owner character varying(100),
    leased_until_utc timestamp with time zone,
    error_message text,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    processed_at_utc timestamp with time zone,
    completed_audio_asset_id bigint,
    CONSTRAINT "PK_audio_generation_queue" PRIMARY KEY (id),
    CONSTRAINT "FK_audio_generation_queue_audio_asset_completed_audio_asset_id" FOREIGN KEY (completed_audio_asset_id) REFERENCES audio_asset (id) ON DELETE SET NULL
);

ALTER TABLE match_score_event ADD tx_audio_context_key character varying(100);

ALTER TABLE match_score_event ADD tx_audio_intensity character varying(30);

ALTER TABLE match_score_event ADD tx_audio_voice_key character varying(80);

ALTER TABLE match_score_event ADD audio_asset_id bigint;

ALTER TABLE match_score_event ADD tx_audio_url text;

ALTER TABLE match_score_event ADD fl_audio_fallback_used boolean NOT NULL DEFAULT FALSE;

ALTER TABLE match_score_event ADD tx_audio_resolved_language character varying(20);

CREATE INDEX "IX_audio_asset_event_type_language_status" ON audio_asset (event_type, language, status);

CREATE INDEX "IX_audio_asset_event_type_language_team_symbol" ON audio_asset (event_type, language, team_symbol);

CREATE INDEX "IX_audio_asset_event_type_language_team_symbol_context_key_int~" ON audio_asset (event_type, language, team_symbol, context_key, intensity, status);

CREATE UNIQUE INDEX "IX_audio_asset_file_hash" ON audio_asset (file_hash) WHERE "file_hash" IS NOT NULL;

CREATE INDEX "IX_audio_generation_queue_completed_audio_asset_id" ON audio_generation_queue (completed_audio_asset_id);

CREATE INDEX "IX_audio_generation_queue_event_type_language_team_symbol_cont~" ON audio_generation_queue (event_type, language, team_symbol, context_key, intensity);

CREATE INDEX "IX_audio_generation_queue_leased_until_utc" ON audio_generation_queue (leased_until_utc);

CREATE INDEX "IX_audio_generation_queue_status_priority_created_at_utc" ON audio_generation_queue (status, priority, created_at_utc);

CREATE UNIQUE INDEX "IX_audio_phrase_template_template_key" ON audio_phrase_template (template_key);

CREATE UNIQUE INDEX "IX_audio_voice_profile_voice_key" ON audio_voice_profile (voice_key);

CREATE INDEX "IX_match_score_event_audio_asset_id" ON match_score_event (audio_asset_id);

ALTER TABLE match_score_event ADD CONSTRAINT "FK_match_score_event_audio_asset_audio_asset_id" FOREIGN KEY (audio_asset_id) REFERENCES audio_asset (id) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260604175603_AddProceduralAudioInfrastructure', '8.0.8');

COMMIT;

