CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE currency (
    cd_currency integer GENERATED BY DEFAULT AS IDENTITY,
    tx_name character varying(50) NOT NULL,
    tx_symbol character varying(50) NOT NULL,
    nr_percentage_change numeric(5,2) NOT NULL,
    dt_last_updated timestamp NOT NULL,
    CONSTRAINT "PK_currency" PRIMARY KEY (cd_currency)
);

CREATE TABLE post_category (
    "Id" integer NOT NULL,
    tx_name character varying(50) NOT NULL,
    CONSTRAINT "PK_post_category" PRIMARY KEY ("Id")
);

CREATE TABLE "user" (
    cd_user integer GENERATED BY DEFAULT AS IDENTITY,
    tx_wallet character varying(50) NOT NULL,
    nm_name character varying(50),
    tx_email character varying(254),
    dt_update timestamp NOT NULL,
    is_human boolean,
    tx_human_captcha character varying(100),
    dt_human_validation timestamp,
    dt_create timestamp with time zone NOT NULL,
    dt_last_login timestamp,
    nm_ia character varying(100),
    nm_human_representative character varying(100),
    nm_company character varying(100),
    nm_ia_model character varying(100),
    nr_balance numeric(18,2) NOT NULL DEFAULT 0.0,
    CONSTRAINT "PK_user" PRIMARY KEY (cd_user)
);

CREATE TABLE team (
    cd_team integer GENERATED BY DEFAULT AS IDENTITY,
    cd_currency integer NOT NULL,
    CONSTRAINT "PK_team" PRIMARY KEY (cd_team),
    CONSTRAINT "FK_team_currency_cd_currency" FOREIGN KEY (cd_currency) REFERENCES currency (cd_currency) ON DELETE CASCADE
);

CREATE TABLE post (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    tx_title character varying(100) NOT NULL,
    tx_url character varying(100) NOT NULL,
    tx_content text NOT NULL,
    dt_post timestamp NOT NULL,
    aq_image bytea NOT NULL,
    post_category_id integer NOT NULL,
    CONSTRAINT "PK_post" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_post_post_category_post_category_id" FOREIGN KEY (post_category_id) REFERENCES post_category ("Id") ON DELETE CASCADE
);

CREATE TABLE pre_sale_purchase (
    id_purchase integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    sol_amount numeric(18,8) NOT NULL,
    ethic_ai_amount numeric(18,8) NOT NULL,
    purchase_date timestamp NOT NULL,
    transaction_hash character varying(100) NOT NULL,
    CONSTRAINT "PK_pre_sale_purchase" PRIMARY KEY (id_purchase),
    CONSTRAINT "FK_pre_sale_purchase_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (cd_user) ON DELETE CASCADE
);

CREATE TABLE match (
    cd_match integer GENERATED BY DEFAULT AS IDENTITY,
    dt_start_time timestamp,
    dt_end_time timestamp,
    cd_team_a integer NOT NULL,
    cd_team_b integer NOT NULL,
    nr_score_a integer NOT NULL,
    nr_score_b integer NOT NULL,
    in_status text NOT NULL,
    CONSTRAINT "PK_match" PRIMARY KEY (cd_match),
    CONSTRAINT "FK_match_team_cd_team_a" FOREIGN KEY (cd_team_a) REFERENCES team (cd_team) ON DELETE RESTRICT,
    CONSTRAINT "FK_match_team_cd_team_b" FOREIGN KEY (cd_team_b) REFERENCES team (cd_team) ON DELETE RESTRICT
);

CREATE TABLE bet (
    cd_bet integer GENERATED BY DEFAULT AS IDENTITY,
    cd_match integer NOT NULL,
    cd_team integer NOT NULL,
    cd_user integer NOT NULL,
    nr_position integer NOT NULL,
    nr_amount numeric(18,2) NOT NULL,
    dt_bet_time timestamp NOT NULL,
    is_claimed boolean NOT NULL DEFAULT FALSE,
    dt_claimed_at timestamp,
    CONSTRAINT "PK_bet" PRIMARY KEY (cd_bet),
    CONSTRAINT "FK_bet_match_cd_match" FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE,
    CONSTRAINT "FK_bet_team_cd_team" FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE,
    CONSTRAINT "FK_bet_user_cd_user" FOREIGN KEY (cd_user) REFERENCES "user" (cd_user) ON DELETE CASCADE
);

INSERT INTO post_category ("Id", tx_name)
VALUES (1, 'Technology');
INSERT INTO post_category ("Id", tx_name)
VALUES (2, 'Science');
INSERT INTO post_category ("Id", tx_name)
VALUES (3, 'Health');
INSERT INTO post_category ("Id", tx_name)
VALUES (4, 'Education');
INSERT INTO post_category ("Id", tx_name)
VALUES (5, 'Business');

CREATE INDEX "IX_bet_cd_match" ON bet (cd_match);

CREATE INDEX "IX_bet_cd_team" ON bet (cd_team);

CREATE INDEX "IX_bet_cd_user" ON bet (cd_user);

CREATE INDEX "IX_match_cd_team_a" ON match (cd_team_a);

CREATE INDEX "IX_match_cd_team_b" ON match (cd_team_b);

CREATE INDEX "IX_post_post_category_id" ON post (post_category_id);

CREATE INDEX "IX_pre_sale_purchase_user_id" ON pre_sale_purchase (user_id);

CREATE INDEX "IX_team_cd_currency" ON team (cd_currency);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250525221104_EthicAIMigration', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE user_team_position (
    cd_position integer GENERATED BY DEFAULT AS IDENTITY,
    cd_user integer NOT NULL,
    cd_team integer NOT NULL,
    nr_principal_allocated decimal(18, 8) NOT NULL,
    nr_current_capital decimal(18, 8) NOT NULL,
    is_auto_compound boolean NOT NULL DEFAULT TRUE,
    in_status integer NOT NULL DEFAULT 0,
    dt_created timestamp with time zone NOT NULL,
    dt_updated timestamp with time zone NOT NULL,
    dt_closed timestamp with time zone,
    CONSTRAINT "PK_user_team_position" PRIMARY KEY (cd_position),
    CONSTRAINT "FK_user_team_position_team_cd_team" FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE,
    CONSTRAINT "FK_user_team_position_user_cd_user" FOREIGN KEY (cd_user) REFERENCES "user" (cd_user) ON DELETE CASCADE
);

ALTER TABLE bet ADD cd_position integer;

CREATE INDEX "IX_user_team_position_cd_team" ON user_team_position (cd_team);

CREATE UNIQUE INDEX "IX_user_team_position_cd_user_cd_team" ON user_team_position (cd_user, cd_team);

CREATE INDEX "IX_bet_cd_position" ON bet (cd_position);

ALTER TABLE bet ADD CONSTRAINT "FK_bet_user_team_position_cd_position" FOREIGN KEY (cd_position) REFERENCES user_team_position (cd_position) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260419190000_UserTeamPositions', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE user_team_position ADD tx_onchain_position character varying(64);

ALTER TABLE user_team_position ADD tx_onchain_vault character varying(64);

ALTER TABLE user_team_position ADD tx_last_onchain_signature character varying(128);

ALTER TABLE user_team_position ADD tx_onchain_cluster character varying(32);

ALTER TABLE user_team_position ADD nr_current_lamports bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420183000_UserTeamPositionOnChainFields', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE match
    ADD COLUMN IF NOT EXISTS in_scoring_rule character varying(40) NOT NULL DEFAULT 'PercentThreshold';

ALTER TABLE currency
    ADD COLUMN IF NOT EXISTS nr_quote_volume decimal(28,8) NOT NULL DEFAULT 0;

ALTER TABLE currency
    ADD COLUMN IF NOT EXISTS nr_trades_count bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS match_score_state (
    cd_match integer NOT NULL PRIMARY KEY,
    nr_thresholds_awarded_a integer NOT NULL DEFAULT 0,
    nr_thresholds_awarded_b integer NOT NULL DEFAULT 0,
    cd_last_percentage_leader integer NULL,
    cd_last_volume_leader integer NULL,
    dt_last_volume_window_start timestamp with time zone NULL,
    dt_last_volume_window_end timestamp with time zone NULL,
    nr_last_event_sequence integer NOT NULL DEFAULT 0,
    dt_last_snapshot_at timestamp with time zone NULL,
    dt_created_at timestamp with time zone NOT NULL,
    dt_updated_at timestamp with time zone NOT NULL,
    CONSTRAINT FK_match_score_state_match_cd_match
        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS match_metric_snapshot (
    cd_match_metric_snapshot bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_match integer NOT NULL,
    cd_team integer NOT NULL,
    dt_captured_at timestamp with time zone NOT NULL,
    nr_percentage_change decimal(18,8) NOT NULL,
    nr_quote_volume decimal(28,8) NOT NULL,
    nr_trade_count bigint NOT NULL,
    CONSTRAINT FK_match_metric_snapshot_match_cd_match
        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE,
    CONSTRAINT FK_match_metric_snapshot_team_cd_team
        FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS match_score_event (
    cd_match_score_event bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_match integer NOT NULL,
    cd_team integer NOT NULL,
    in_rule_type character varying(40) NOT NULL,
    tx_event_type character varying(80) NOT NULL,
    tx_reason_code character varying(80) NULL,
    nr_points integer NOT NULL,
    nr_event_sequence integer NOT NULL,
    nr_team_percentage_change decimal(18,8) NULL,
    nr_opponent_percentage_change decimal(18,8) NULL,
    nr_team_quote_volume decimal(28,8) NULL,
    nr_opponent_quote_volume decimal(28,8) NULL,
    nr_metric_delta decimal(28,8) NULL,
    dt_window_start timestamp with time zone NULL,
    dt_window_end timestamp with time zone NULL,
    tx_description text NOT NULL,
    dt_event_time timestamp with time zone NOT NULL,
    CONSTRAINT FK_match_score_event_match_cd_match
        FOREIGN KEY (cd_match) REFERENCES match (cd_match) ON DELETE CASCADE,
    CONSTRAINT FK_match_score_event_team_cd_team
        FOREIGN KEY (cd_team) REFERENCES team (cd_team) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_match_metric_snapshot_cd_match_cd_team_dt_captured_at
    ON match_metric_snapshot (cd_match, cd_team, dt_captured_at);

CREATE INDEX IF NOT EXISTS IX_match_metric_snapshot_cd_team
    ON match_metric_snapshot (cd_team);

CREATE UNIQUE INDEX IF NOT EXISTS IX_match_score_event_cd_match_nr_event_sequence
    ON match_score_event (cd_match, nr_event_sequence);

CREATE INDEX IF NOT EXISTS IX_match_score_event_cd_team
    ON match_score_event (cd_team);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260421150000_MatchScoringModes', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS tx_blockchain_mode_snapshot character varying(32);

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS in_exposure_mode integer NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_pnl decimal(18, 8) NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_wins integer NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_losses integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS position_allocation (
    id_position_allocation integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
    cd_match integer NOT NULL REFERENCES match (cd_match) ON DELETE CASCADE,
    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
    nr_allocated_amount decimal(18, 8) NOT NULL,
    nr_result_amount decimal(18, 8) NULL,
    nr_pnl decimal(18, 8) NULL,
    in_status integer NOT NULL DEFAULT 0,
    dt_created timestamp with time zone NOT NULL,
    dt_settled timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_position_allocation_cd_position_cd_match
    ON position_allocation (cd_position, cd_match);

CREATE UNIQUE INDEX IF NOT EXISTS IX_position_allocation_cd_bet
    ON position_allocation (cd_bet)
    WHERE cd_bet IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_position_allocation_cd_match
    ON position_allocation (cd_match);

CREATE TABLE IF NOT EXISTS position_lifecycle_event (
    id_position_lifecycle_event integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
    cd_match integer NULL REFERENCES match (cd_match) ON DELETE SET NULL,
    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
    in_event_type integer NOT NULL,
    nr_amount decimal(18, 8) NULL,
    nr_capital_before decimal(18, 8) NULL,
    nr_capital_after decimal(18, 8) NULL,
    nr_pnl decimal(18, 8) NULL,
    tx_notes text NULL,
    dt_created timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_position_dt_created
    ON position_lifecycle_event (cd_position, dt_created);

CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_match
    ON position_lifecycle_event (cd_match);

CREATE INDEX IF NOT EXISTS IX_position_lifecycle_event_cd_bet
    ON position_lifecycle_event (cd_bet);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509193000_PersistentPositionLayer', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS nr_pressure_charges_a integer NOT NULL DEFAULT 0;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS nr_pressure_charges_b integer NOT NULL DEFAULT 0;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS nr_pressure_goals_awarded integer NOT NULL DEFAULT 0;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS cd_last_pressure_leader integer NULL;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS nr_last_pressure_leader_cycles integer NOT NULL DEFAULT 0;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS dt_last_pressure_goal_a timestamp with time zone NULL;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS dt_last_pressure_goal_b timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260513113000_AddArenaPressureColumnsToMatchScoreState', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE arena_sentiment_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    symbol character varying(30) NOT NULL,
    score integer NOT NULL,
    classification character varying(40) NOT NULL,
    price_momentum_score numeric(10,2),
    volume_score numeric(10,2),
    order_book_score numeric(10,2),
    funding_score numeric(10,2),
    long_short_score numeric(10,2),
    volatility_score numeric(10,2),
    data_coverage numeric(10,2) NOT NULL,
    has_sufficient_data boolean NOT NULL,
    calculated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_arena_sentiment_snapshot" PRIMARY KEY (id)
);

CREATE INDEX "IX_arena_sentiment_snapshot_symbol_calculated_at" ON arena_sentiment_snapshot (symbol, calculated_at);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514100000_AddArenaSentimentSnapshot', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE match_ai_narration_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    match_id integer NOT NULL,
    event_type character varying(80) NOT NULL,
    culture character varying(20) NOT NULL,
    text text NOT NULL,
    prompt_hash character varying(128),
    context_hash character varying(128),
    source character varying(20) NOT NULL,
    model character varying(80),
    created_at_utc timestamp with time zone NOT NULL,
    hot_score_snapshot integer,
    left_score_snapshot integer,
    right_score_snapshot integer,
    leader_symbol_snapshot character varying(30),
    metadata_json text,
    CONSTRAINT "PK_match_ai_narration_history" PRIMARY KEY (id),
    CONSTRAINT "FK_match_ai_narration_history_match_match_id" FOREIGN KEY (match_id) REFERENCES match (cd_match) ON DELETE CASCADE
);

CREATE INDEX "IX_match_ai_narration_history_match_id_created_at_utc" ON match_ai_narration_history (match_id, created_at_utc);

CREATE INDEX "IX_match_ai_narration_history_match_id_event_type_context_hash" ON match_ai_narration_history (match_id, event_type, context_hash);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514143000_AddMatchAiNarrationHistory', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS cd_current_pressure_dominance_leader integer NULL;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS dt_current_pressure_dominance_started timestamp with time zone NULL;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS fl_current_pressure_dominance_resolved boolean NOT NULL DEFAULT FALSE;

ALTER TABLE match_score_state
    ADD COLUMN IF NOT EXISTS fl_current_pressure_dominance_goal_awarded boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260529153000_AddArenaPressureDominanceState', '8.0.8');

COMMIT;

START TRANSACTION;

CREATE TABLE audio_asset (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    team_symbol character varying(20),
    context_key character varying(100),
    intensity character varying(30),
    voice_key character varying(80),
    template_key character varying(100),
    text_prompt text,
    audio_url text NOT NULL,
    relative_path text NOT NULL,
    file_name character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL DEFAULT 'audio/mpeg',
    duration_ms integer,
    file_size_bytes bigint,
    file_hash character varying(128),
    generation_model character varying(100),
    generation_source character varying(50),
    quality_score numeric(5,2),
    priority integer NOT NULL DEFAULT 0,
    usage_count integer NOT NULL DEFAULT 0,
    status character varying(30) NOT NULL DEFAULT 'ready',
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    last_used_at_utc timestamp with time zone,
    CONSTRAINT "PK_audio_asset" PRIMARY KEY (id)
);

CREATE TABLE audio_phrase_template (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    template_key character varying(100) NOT NULL,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    context_key character varying(100),
    intensity character varying(30),
    template_text text NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    priority integer NOT NULL DEFAULT 0,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audio_phrase_template" PRIMARY KEY (id)
);

CREATE TABLE audio_voice_profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    voice_key character varying(80) NOT NULL,
    language character varying(10) NOT NULL,
    display_name character varying(150) NOT NULL,
    sample_relative_path text NOT NULL,
    sample_url text NOT NULL,
    provider character varying(80),
    voice_style character varying(80),
    is_active boolean NOT NULL DEFAULT TRUE,
    priority integer NOT NULL DEFAULT 0,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audio_voice_profile" PRIMARY KEY (id)
);

CREATE TABLE audio_generation_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type character varying(50) NOT NULL,
    language character varying(10) NOT NULL,
    team_symbol character varying(20),
    context_key character varying(100),
    intensity character varying(30),
    voice_key character varying(80) NOT NULL,
    template_key character varying(100),
    text_prompt text NOT NULL,
    target_relative_path text,
    target_file_name character varying(255),
    status character varying(30) NOT NULL DEFAULT 'pending',
    priority integer NOT NULL DEFAULT 0,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 3,
    lease_owner character varying(100),
    leased_until_utc timestamp with time zone,
    error_message text,
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    processed_at_utc timestamp with time zone,
    completed_audio_asset_id bigint,
    CONSTRAINT "PK_audio_generation_queue" PRIMARY KEY (id),
    CONSTRAINT "FK_audio_generation_queue_audio_asset_completed_audio_asset_id" FOREIGN KEY (completed_audio_asset_id) REFERENCES audio_asset (id) ON DELETE SET NULL
);

ALTER TABLE match_score_event ADD tx_audio_context_key character varying(100);

ALTER TABLE match_score_event ADD tx_audio_intensity character varying(30);

ALTER TABLE match_score_event ADD tx_audio_voice_key character varying(80);

ALTER TABLE match_score_event ADD audio_asset_id bigint;

ALTER TABLE match_score_event ADD tx_audio_url text;

ALTER TABLE match_score_event ADD fl_audio_fallback_used boolean NOT NULL DEFAULT FALSE;

ALTER TABLE match_score_event ADD tx_audio_resolved_language character varying(20);

CREATE INDEX "IX_audio_asset_event_type_language_status" ON audio_asset (event_type, language, status);

CREATE INDEX "IX_audio_asset_event_type_language_team_symbol" ON audio_asset (event_type, language, team_symbol);

CREATE INDEX "IX_audio_asset_event_type_language_team_symbol_context_key_int~" ON audio_asset (event_type, language, team_symbol, context_key, intensity, status);

CREATE UNIQUE INDEX "IX_audio_asset_file_hash" ON audio_asset (file_hash) WHERE "file_hash" IS NOT NULL;

CREATE INDEX "IX_audio_generation_queue_completed_audio_asset_id" ON audio_generation_queue (completed_audio_asset_id);

CREATE INDEX "IX_audio_generation_queue_event_type_language_team_symbol_cont~" ON audio_generation_queue (event_type, language, team_symbol, context_key, intensity);

CREATE INDEX "IX_audio_generation_queue_leased_until_utc" ON audio_generation_queue (leased_until_utc);

CREATE INDEX "IX_audio_generation_queue_status_priority_created_at_utc" ON audio_generation_queue (status, priority, created_at_utc);

CREATE UNIQUE INDEX "IX_audio_phrase_template_template_key" ON audio_phrase_template (template_key);

CREATE UNIQUE INDEX "IX_audio_voice_profile_voice_key" ON audio_voice_profile (voice_key);

CREATE INDEX "IX_match_score_event_audio_asset_id" ON match_score_event (audio_asset_id);

ALTER TABLE match_score_event ADD CONSTRAINT "FK_match_score_event_audio_asset_audio_asset_id" FOREIGN KEY (audio_asset_id) REFERENCES audio_asset (id) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260604175603_AddProceduralAudioInfrastructure', '8.0.8');

COMMIT;

