using System.Text.Json;
using Npgsql;

var configPath = Path.Combine(Directory.GetCurrentDirectory(), "CriptoVersus.API", "appsettings.Development.json");
var json = await File.ReadAllTextAsync(configPath);
using var doc = JsonDocument.Parse(json);

if (!doc.RootElement.TryGetProperty("ConnectionStrings", out var connectionStrings)
    || !connectionStrings.TryGetProperty("Default", out var defaultConnection))
{
    throw new InvalidOperationException("ConnectionStrings:Default nao encontrada.");
}

var connectionString = defaultConnection.GetString();
if (string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("Connection string local vazia.");

const string sql = """
CREATE TABLE IF NOT EXISTS social_post_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id integer NOT NULL,
    platform character varying(30) NOT NULL,
    post_text text NOT NULL,
    post_url character varying(500),
    external_post_id character varying(200),
    hot_score integer NOT NULL,
    reason text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_social_post_history_match_match_id
        FOREIGN KEY (match_id)
        REFERENCES match (cd_match)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_social_post_history_match_id_platform_created_at
    ON social_post_history (match_id, platform, created_at);
""";

await using var connection = new NpgsqlConnection(connectionString);
await connection.OpenAsync();

await using var command = new NpgsqlCommand(sql, connection);
await command.ExecuteNonQueryAsync();

const string verifySql = """
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'social_post_history'
);
""";

await using var verifyCommand = new NpgsqlCommand(verifySql, connection);
var exists = (bool)(await verifyCommand.ExecuteScalarAsync() ?? false);

Console.WriteLine(exists ? "social_post_history criada/verificada com sucesso." : "Falha ao verificar social_post_history.");
