using System.Text.Json;
using Npgsql;

var configPath = Path.Combine(Directory.GetCurrentDirectory(), "CriptoVersus.API", "appsettings.Development.json");
var json = await File.ReadAllTextAsync(configPath);
using var doc = JsonDocument.Parse(json);

if (!doc.RootElement.TryGetProperty("ConnectionStrings", out var connectionStrings)
    || !connectionStrings.TryGetProperty("Default", out var defaultConnection))
{
    throw new InvalidOperationException("ConnectionStrings:Default nao encontrada.");
}

var connectionString = defaultConnection.GetString();
if (string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("Connection string local vazia.");

const string sql = """
ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS tx_blockchain_mode_snapshot character varying(32);

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS in_exposure_mode integer NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_pnl numeric(18, 8) NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_wins integer NOT NULL DEFAULT 0;

ALTER TABLE user_team_position
    ADD COLUMN IF NOT EXISTS nr_total_losses integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS position_allocation (
    id_position_allocation integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
    cd_match integer NOT NULL REFERENCES match (cd_match) ON DELETE CASCADE,
    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
    nr_allocated_amount numeric(18, 8) NOT NULL,
    nr_result_amount numeric(18, 8) NULL,
    nr_pnl numeric(18, 8) NULL,
    in_status integer NOT NULL DEFAULT 0,
    dt_created timestamp with time zone NOT NULL,
    dt_settled timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_position_allocation_cd_position_cd_match
    ON position_allocation (cd_position, cd_match);

CREATE UNIQUE INDEX IF NOT EXISTS ix_position_allocation_cd_bet
    ON position_allocation (cd_bet)
    WHERE cd_bet IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_position_allocation_cd_match
    ON position_allocation (cd_match);

CREATE TABLE IF NOT EXISTS position_lifecycle_event (
    id_position_lifecycle_event integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cd_position integer NOT NULL REFERENCES user_team_position (cd_position) ON DELETE CASCADE,
    cd_match integer NULL REFERENCES match (cd_match) ON DELETE SET NULL,
    cd_bet integer NULL REFERENCES bet (cd_bet) ON DELETE SET NULL,
    in_event_type integer NOT NULL,
    nr_amount numeric(18, 8) NULL,
    nr_capital_before numeric(18, 8) NULL,
    nr_capital_after numeric(18, 8) NULL,
    nr_pnl numeric(18, 8) NULL,
    tx_notes text NULL,
    dt_created timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_position_lifecycle_event_cd_position_dt_created
    ON position_lifecycle_event (cd_position, dt_created);

CREATE INDEX IF NOT EXISTS ix_position_lifecycle_event_cd_match
    ON position_lifecycle_event (cd_match);

CREATE INDEX IF NOT EXISTS ix_position_lifecycle_event_cd_bet
    ON position_lifecycle_event (cd_bet);
""";

await using var connection = new NpgsqlConnection(connectionString);
await connection.OpenAsync();

await using var command = new NpgsqlCommand(sql, connection);
await command.ExecuteNonQueryAsync();

const string verifySql = """
SELECT
    EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'position_allocation'
    ) AS has_position_allocation,
    EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'position_lifecycle_event'
    ) AS has_position_lifecycle_event,
    EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'user_team_position'
          AND column_name = 'in_exposure_mode'
    ) AS has_exposure_mode;
""";

await using var verifyCommand = new NpgsqlCommand(verifySql, connection);
await using var reader = await verifyCommand.ExecuteReaderAsync();

if (!await reader.ReadAsync())
    throw new InvalidOperationException("Falha ao verificar o schema local.");

var hasPositionAllocation = reader.GetBoolean(0);
var hasPositionLifecycleEvent = reader.GetBoolean(1);
var hasExposureMode = reader.GetBoolean(2);

Console.WriteLine(
    hasPositionAllocation && hasPositionLifecycleEvent && hasExposureMode
        ? "Persistent position layer aplicada com sucesso no banco local."
        : "Falha parcial ao verificar persistent position layer.");
